#!/bin/bash
#This script replaces #placeholders in SetupNeutron.template with the values found in Vagrantfile.yml to generate "SetupNeutron"

eval $(./parse_yaml Vagrantfile.yml)

export cidr_convert=$(./maskconv $netmask)

eval "cat <<EOF
$(<SetupNeutron.template)
EOF
" 2> /dev/null > SetupNeutron

chmod +x SetupNeutron
