#!/bin/bash

set -x
yum install -y http://rdo.fedorapeople.org/rdo-release.rpm
yum install -y openstack-packstack expect 

/usr/bin/packstack --answer-file=/vagrant/ans.txt

cp /root/keystonerc_admin /vagrant

eval $(./parse_yaml Vagrantfile.yml)
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null  root@"$compute_bridged_ip" '/vagrant/switch_to_qemu.sh'

