#!/bin/bash

if [[ $(whoami) != "root" ]]
then
  echo "This script must be run as root"
  exit 1
fi

eval $(./parse_yaml Vagrantfile.yml)
peip=${neutron_router_start%.*};
export network="$peip".0


set -v
ifdown eth1
yes | cp /vagrant/ifcfg-eth1 /etc/sysconfig/network-scripts/
ifup eth1
ip route del default
ip route add default via "$gateway"
route add -net $network netmask 255.255.255.0 gw $neutron_router_start

