#!/bin/bash

if [[ $(whoami) != "root" ]]
then
      echo "This script must be run as root"
      exit 1
fi

set -e
set -v
cd /vagrant
./build_SetupNeutron
./SetupNeutron
./SwitchToQemu
./CreateAndSourceKey
./GetCirrosMinimalImage
sleep 15 #Place holder for actual logic. 
./LaunchCirrosVM cirros
