#!/bin/bash
set -e
set -v
cd /vagrant
./build_SetupNeutron
./SetupNeutron
./SwitchToQemu
./CreateAndSourceKey
./GetCirrosMinimalImage
sleep 15 #Place holder for actual logic. 
./LaunchCirrosVM cirros
