#!/bin/bash

set -v

source /vagrant/keystonerc_admin


#Creating a subnet
#Create router and network, assign a subnet and add router to the subnet

neutron router-create router1
neutron net-create internal_network1
neutron subnet-create internal_network1 172.17.0.0/24 --name subinternal_network1
neutron router-interface-add router1 subinternal_network1


#Attach to a public subnet (to my home router (it will handle dhcp)
neutron net-create external_network1 --router:external=True

neutron subnet-create external_network1 192.168.0.0/22 \
  --name subexternal_network1 --enable_dhcp=False \
  --allocation-pool start=192.168.3.1,end=192.168.3.128 --gateway=192.168.0.1

neutron router-gateway-set router1 external_network1

#https://ask.openstack.org/en/question/9592/disabling-security-groups-in-horizon/
neutron security-group-rule-create --protocol icmp default
neutron security-group-rule-create --protocol tcp --port-range-min 22 --port-range-max 22 default
#nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0
#nova secgroup-add-rule default tcp 22 22 0.0.0.0/0

#list created networks

neutron net-list  | grep [a-z] | awk '{print $4,$7}' | grep -v name
route add -net 192.168.3.0 netmask 255.255.255.0 gw 192.168.3.1
echo "GATEWAYDEV=br-ex" >> /etc/sysconfig/network
echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-br-ex
nova secgroup-list-rules default
neutron router-show router1

